
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'msb_demo'
version: '1.0.0'

config-version: 2

profile: spark_profile

model-paths: ["models"]
test-paths: ["tests"]

models:
  customer_dbt:
    +materialized: table
    +file_format: delta
    +location_root: "s3a://warehouse/silver"
